### ISSUE TITLE
Incomplete ambiguous dna expansion

### ISSUE THREAD

**Issue by bricoletc** [rmcolq/make_prg#12]
I'm delving into `make_prg` some more because looking at interoperability with gramtools, and have found the following behaviour from function `get_interval_seqs`: 

- If you give it the sequence 'RWAAT' it expands to `{"GAAAT", "AAAAT", "GTAAT", "ATAAT"}`
- If you give it the sequence `RRAAT` it expands to `{"GGAAT","AAAAT"}`

The former is complete, the latter is not: missing GAAAT and AGAAT.

(R is ambiguous IUPAC for either G or A)
(Not showing a failing test case because the one I have made is in refactored code)

Is this deliberate?

I am assuming not and have already made a fix which i'll PR in if I get confirmation

**Comment by rmcolq** [comment]
It's not deliberate - feel free to PR and merge in your fix!
