### ISSUE TITLE
Should lowercase valid base raise error

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/make_prg#7]
I am incrementally improving our test coverage and have a question relating to some code from @bricoletc 

https://github.com/rmcolq/make_prg/blob/86dbeebd02a7d7350700cd65874e244130aeda9a/make_prg/utils.py#L144-L146

If the `input_char` is lowercase but valid base then we will raise an `AssertionError` here. Is this the intended behaviour or, should we treat all input as uppercase?

**Comment by mbhall88** [comment]
Effectively, this is the test case I have. Should this test pass or fail?

```py
def test_DNAtoInt_char_valid_but_lowercase_returns_int(self):
    encoder = IntegerEncoder()
    char = "a"

    actual = encoder._DNA_to_int(char)
    expected = 1

    self.assertEqual(actual, expected)
```

**Comment by bricoletc** [comment]
Hey @mbhall88 , I did not have in mind that the input should be uppercase, and think we should .upper() for example

**Comment by mbhall88** [comment]
Ok. I have a fix incoming.
